version: '2'

services:
  lang-uk:
    build: .
    ports:
      - 8080:8080
    links:
    - ner-ms-uk
    - ner-ms-en
    - tokenize-ms
  ner-ms-uk:
    image: chaliy/ner-ms:uk
    ports:
      - '8080'
  ner-ms-en:
    image: chaliy/ner-ms:en
    ports:
      - '8080'
  tokenize-ms:
    image: chaliy/tokenize-ms
    ports:
      - '8080'
